version: "2"
services:
  db:
    container_name: mysql-socle-javaee-rec
    image: mysql:5.7
    ports: 
      - 4001:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: socle
    networks:
      app_net:
        ipv4_address: 10.0.1.2
  web:
    container_name: tomcat-socle-javaee-rec
    build: .
    image: tomcat-socle-javaee:$VERSION
    ports:
      - 8001:8080
    links:
      - db
    networks:
      app_net:
        ipv4_address: 10.0.1.3
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.1.0/24
        gateway: 10.0.1.1
